### ISSUE TITLE
The evaluation setting of the full scene rendering. 

### ISSUE THREAD

**Issue by W-Ted** [zju3dv/object_nerf#13]
Hi, thanks for the nice paper and code!

I have one question about the evaluation setting of the full scene rendering (novel view synthesis). In Table.1 of the paper, quantitative metrics are compared. Are these metrics computed only on the test set, I mean, the frames listed in datasets/split/xxx/test.txt? 

Thanks in advance!

**Comment by ybbbbt** [comment]
[object_nerf_evaluation.zip](https://github.com/zju3dv/object_nerf/files/9259657/object_nerf_evaluation.zip)
Hi, W-Ted,
I have uploaded the rendered file for comparison. We use a subset of the test file for evaluation (as the test split file in the uploaded zip file).

**Comment by W-Ted** [comment]
Hi, Bangbang. Thank you very much for your reply!
