### ISSUE TITLE
About Pose Matrixs Transformation

### ISSUE THREAD

**Issue by CeoiZidung** [zju3dv/object_nerf#14]
Hello, thanks u for awesome work.

I have some confusion about the Pose matrixs transformation among world, camera, objects. I cannot understand the meaning behind them. I wanna ask if there are some blogs i can refer to ?

Thanks in advance~

**Comment by ybbbbt** [comment]
Hi, CeoiZidung,
We use the notations for poses similar to SLAM systems, i.e., you can search for `transformation SLAM Tcw Twc` as a reference.

**Comment by CeoiZidung** [comment]
> transformation SLAM Tcw Twc

Thanks u！
