### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.ao'

### ISSUE THREAD

**Issue by hengfei-wang** [zju3dv/object_nerf#15]
Hi,

I installed the conda env according to the readme file. But I got this error msg "ModuleNotFoundError: No module named 'torch.ao'" when I try to run training code on toy_desk_2 demo. 

Does anyone have the same problem?

Thanks

**Comment by ybbbbt** [comment]
Hi hengfei-wang,

I'm sorry for the running issue.

Can you share your conda environment file?

Here is my conda environment: https://github.com/zju3dv/object_nerf/issues/11#issuecomment-1193954792.

**Comment by hengfei-wang** [comment]
Hi,

I rebuilt env according to you env file. And I removed readline and pillow's version request because conda reported there is a conflict in these modules' version. But problem remains and error msg is same.

This is my env file: [my_env.yaml.txt](https://github.com/zju3dv/object_nerf/files/9312113/my_env.yaml.txt)

**Comment by hengfei-wang** [comment]
Well, I guess I have solved the problem. It's because the mismatch between pytorch and pytorch-lightning. I installed newest version of pytorch using conda. After that, I installed pytorch-lightning using conda, but it installed very old version by default. So I upgraded pytorch-lightning to 1.5.4 by myself even though it takes several mins for conda to parse the environment.
