### ISSUE TITLE
How to get bbox.json?

### ISSUE THREAD

**Issue by SuzyZhao0417** [zju3dv/object_nerf#18]
I want to label other scenes, how to get bbox.json?

**Comment by yyashpatel** [comment]
Were able to figure out how to get bbox.json ?
I would like to know what is the frame of reference used to define the bbox ?

**Comment by rockywind** [comment]
How can I generate the bbox.json on our own dataset?

**Comment by rockywind** [comment]
@JiamingSuen @MrMorning 
Hi, how to generate the bbox.json?
