### ISSUE TITLE
This is an exciting work. When will you release the code?

### ISSUE THREAD

**Issue by zhanghongyong123456** [zju3dv/object_nerf#2]

**Comment by JingwenWang95** [comment]
Hi, any updates about the code release? @ybbbbt

**Comment by ybbbbt** [comment]
Sorry for the late reply. We plan to release the code at the end of this month or early next month.

**Comment by JingwenWang95** [comment]
Great! Thanks for clarification!

**Comment by TontonTremblay** [comment]
Thank you, putting down a comment to get a notification when code is available. Looking forward playing with it.

**Comment by FreemanTom** [comment]
> Thank you, putting down a comment to get a notification when code is available. Looking forward playing with it. Excellent work btw.

Me too. Looking forward to the code released!

**Comment by KelestZ** [comment]
Hi, shall the dataset have  'poses_bounds.npy'? I couldn't find this file from the provided link of ToyDesk dataset.

**Comment by hengfei-wang** [comment]
Hi, hope to see the code :)

**Comment by liujiaheng** [comment]
@ybbbbt Hi, this is a great work, when will the code be released?

**Comment by ybbbbt** [comment]
Sorry for the delay.
