### ISSUE TITLE
How to move the objects in the scene?

### ISSUE THREAD

**Issue by rockywind** [zju3dv/object_nerf#22]
Hi,
I don't find the `edit_type == move`.
Can you show me the detailed tutorial for moveing objects?
![image](https://user-images.githubusercontent.com/14838781/222619727-f1473bc0-3cdd-4ec3-a668-9385716202b0.png)

**Comment by ybbbbt** [comment]
Hi, you can customize `trans_pose` as you like, such as https://github.com/zju3dv/object_nerf/blob/e8b1a7a5ab0596babdf4400a9e8908f1bfdcf990/test/demo_editable_render.py#L37.

**Comment by rockywind** [comment]
Thanks!
