### ISSUE TITLE
Camera intrisics

### ISSUE THREAD

**Issue by chenhonghua** [zju3dv/object_nerf#26]
Dear authors,

Thanks for your impressive work and released dataset.

I am trying to use the toydesk_data. But I wanna have the camera's intrinsic parameters. 

So, could you please share it with me? Or tell me how to compute them! 

Thank you very much!

**Comment by pipyat** [comment]
In case this dataset is still of interest to you - you can obtain the intrinsics by importing the reconstruction (.bin files provided) into COLMAP before exporting the model as .txt - intrinsics will be contained within cameras.txt
