### ISSUE TITLE
How to handle the dataset.

### ISSUE THREAD

**Issue by WithBella** [zju3dv/object_nerf#27]
Hi, I am a newbie to NeRF. I would like to know how to handle this dataset?  

The description in[Data Preparation](https://github.com/zju3dv/object_nerf/tree/main/data_preparation) is a bit confusing, do I need to manually convert the dataset from OpenCV format to NDC format? Or is the downloadable dataset already processed?

Also, the download link for scannet_train_detection_data is no longer available, could you please upload it again?

All your help is greatly appreciated.

**Comment by Magical1-zyz** [comment]
Hi,I am a newbie to NeRF too.
I see you have completed your issue, did you solve your question?
I have the same issue, so I can't run this project.
All your help is greatly appreciated.

**Comment by RuihanLu** [comment]
For Toydesk Dataset, you can use the data they upload directly without any process.

For ScanNet Dataset you need to download the origin dataset ScanNet V2 and the processed version from this repo.

**Comment by Magical1-zyz** [comment]
Thank you,I'll try it again

**Comment by Magical1-zyz** [comment]
I have some error when I  tran the model.Should I change the path in the code.
I have the following warnings.
UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')
UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: data/toy_desk/our_desk_2/pcd_from_mesh.ply

**Comment by RuihanLu** [comment]
> I have some error when I tran the model.Should I change the path in the code. I have the following warnings. UserWarning: No audio backend is available. warnings.warn('No audio backend is available.') UserWarning: torchaudio C++ extension is not available. warnings.warn('torchaudio C++ extension is not available.') RPly: Unable to open file [Open3D WARNING] Read PLY failed: unable to open file: data/toy_desk/our_desk_2/pcd_from_mesh.ply

Yes. I guess the author's file structure is a little bit different from this repo, so you need to check and fix it.
Maybe you can reference my repo[https://github.com/RuihanLu/EditableObjectNeRF] to get a structure that can work. It's some of my attempts at Object-NeRF, and I rewrote part of the readme that was confusing me, i guess that will be helpful for you.

**Comment by Magical1-zyz** [comment]
Thanks again, I'll reference yours to try it again.

**Comment by Wakeelfahmed** [comment]
> For Toydesk Dataset, you can use the data they upload directly without any process.
> 
> For ScanNet Dataset you need to download the origin dataset ScanNet V2 and the processed version from this repo.

Hi, can u explain how to use it, I have downloaded both the dataset and unzipped, what's next?
