### ISSUE TITLE
Dataset Format / Pointcloud

### ISSUE THREAD

**Issue by weders** [zju3dv/object_nerf#6]
Hi, 

Thanks a lot for releasing this code!

When trying to get it running on my own data, I realized that the data preparation instructions are a bit unclear. If I have a dataset in the LLFF format. Do I need to transform it into the COLMAP format? 

Further, is there a way to use the voxel embeddings without knowing the point cloud of the scene a priori?

Thanks!

**Comment by ybbbbt** [comment]
Hi, weders.

Sorry that we haven't supported LLFF data format. But you can prepare the dataset in the form of nerf_synthetic (e.g., with camera poses, frame indices and image paths defined in a transform.json as our ToyDesk dataset).
Note that the LLFF dataloader usually comes with automatically pose centralization and near/far plane computation, while our dataloader requires manually assigning `scale_factor`, `scene_center` and `near, far` in the config file.

For the scene without point clouds, you can disable the `use_voxel_embedding` option at first, which might slightly decrease rendering details but still works fine with object-center learning.
