### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by luoshunli** [zju3dv/object_nerf#7]
Hi: 
    When I train toy_desk datasets, I meet the problem. 
     
     assertError on here
     idx_occu = torch.nonzero(self.voxel_occupancy)
     assert self.embedding_space_ftr.num_embeddings >= idx_occu.shape[0]
  
     Can you help me solve the problem?

**Comment by ybbbbt** [comment]
Hi, luoshunli:

Can you provide the command of your training?

I guess you can increase the `voxel_size` or enlarge the `N_max_voxels` in the config file to solve this issue.

By the way, does the `pcd_path` in config yaml correctly point to the real ply file?

**Comment by luoshunli** [comment]
Thank you! I have solved the problem by enlarge the N_max_voxels.
