### ISSUE TITLE
The content of scene branck.

### ISSUE THREAD

**Issue by YutingXiao** [zju3dv/object_nerf#8]
Hi, Thanks for the code!

I use extract_mesh.py to extract the mesh of the scene branch and I find that the objects also exist in the scene branch. But the Figure 1 in the paper shows that the scene branch only has the background.

So, the scene branch only has "background" or "background + objects"?

**Comment by ybbbbt** [comment]
Hi Yuting:

Yes, the scene branch encodes the entire scene, so the objects and the background are both included. We render the background by simply pruning ray samples inside bounding boxes of user-defined regions.
Sorry for the confusion.
